// Diccionario de la INTERFAZ general (es → en) para la traducción en runtime.
// Solo frases de UI (navegación, botones, títulos, etiquetas, tooltips). NO se
// traducen los contenidos dinámicos (mensajes de chat, textos de flujos,
// descripciones, prompts): esas zonas se marcan con [data-i18n-skip].
//
// La clave es el texto EXACTO en español (sin emojis ni símbolos al inicio:
// el traductor separa el prefijo de emoji/símbolo y traduce el núcleo).
// Para añadir cobertura, agrega aquí más pares "Español": "English".

export const UI_ES_EN = {
  // ── Navegación principal / shells ─────────────────────────────────────────
  'Inbox': 'Inbox',
  'CRM': 'CRM',
  'Masivos': 'Bulk',
  'Mensajes masivos': 'Bulk messages',
  'Flujos': 'Flows',
  'Zona IA': 'AI Zone',
  'Configuración': 'Settings',
  'Métricas': 'Metrics',
  'Equipo': 'Team',
  'Chat de Equipo': 'Team Chat',
  'Chat de equipo': 'Team chat',
  'Soporte': 'Support',
  'Soporte AVI': 'AVI Support',
  'Plataforma': 'Platform',
  'Cuentas': 'Accounts',
  'Cuenta': 'Account',
  'Usuarios': 'Users',
  'Usuario': 'User',
  'Integraciones': 'Integrations',
  'Pricing IA': 'AI Pricing',
  'Generador': 'Generator',
  'Super Admins': 'Super Admins',
  'Super Admin': 'Super Admin',
  'Documentación': 'Documentation',
  'Tutoriales': 'Tutorials',
  'Comunicación': 'Communication',
  'Cambiar cuenta': 'Switch account',
  'Cambiar cuenta ▾': 'Switch account ▾',
  'Cuentas — A·Z': 'Accounts — A·Z',
  'Prompt activo:': 'Active prompt:',
  'Vista como Owner': 'Viewing as Owner',
  'Volver': 'Back',
  'Activo': 'Active',
  'Borrador': 'Draft',
  'Sin cuentas asignadas': 'No accounts assigned',
  'sin prompt activo': 'no active prompt',
  'Canales en línea': 'Channels online',
  'Canales conectando...': 'Channels connecting...',
  'Canales error': 'Channels error',

  // ── Acciones comunes ──────────────────────────────────────────────────────
  'Guardar': 'Save',
  'Guardar cambios': 'Save changes',
  'Guardar borrador': 'Save draft',
  'Cancelar': 'Cancel',
  'Eliminar': 'Delete',
  'Editar': 'Edit',
  'Enviar': 'Send',
  'Enviar respuesta': 'Send reply',
  'Cerrar': 'Close',
  'Cerrar sesión': 'Log out',
  'Buscar': 'Search',
  'Buscar...': 'Search...',
  'Cargando': 'Loading',
  'Cargando...': 'Loading...',
  'Cargando…': 'Loading…',
  'Crear': 'Create',
  'Crear agente': 'Create agent',
  'Nuevo': 'New',
  'Nueva': 'New',
  'Añadir': 'Add',
  'Agregar': 'Add',
  'Quitar': 'Remove',
  'Aceptar': 'Accept',
  'Confirmar': 'Confirm',
  'Aplicar': 'Apply',
  'Continuar': 'Continue',
  'Atrás': 'Back',
  'Siguiente': 'Next',
  'Anterior': 'Previous',
  'Sí': 'Yes',
  'No': 'No',
  'Todos': 'All',
  'Todas': 'All',
  'Ninguno': 'None',
  'Ver': 'View',
  'Ver más': 'See more',
  'Ver perfil': 'View profile',
  'Detalles': 'Details',
  'Opciones': 'Options',
  'Copiar': 'Copy',
  'Copiado': 'Copied',
  'Descargar': 'Download',
  'Subir': 'Upload',
  'Importar': 'Import',
  'Exportar': 'Export',
  'Actualizar': 'Refresh',
  'Recargar': 'Reload',
  'Probar': 'Test',
  'Conectar': 'Connect',
  'Desconectar': 'Disconnect',
  'Activar': 'Enable',
  'Desactivar': 'Disable',
  'Reabrir': 'Reopen',
  'Revocar': 'Revoke',
  'Asignar': 'Assign',
  'Sin asignar': 'Unassigned',
  'Nombre': 'Name',
  'Descripción': 'Description',
  'Estado': 'Status',
  'Tipo': 'Type',
  'Canal': 'Channel',
  'Fecha': 'Date',
  'Acciones': 'Actions',
  'Etiquetas': 'Tags',
  'Etiqueta': 'Tag',
  'Filtros': 'Filters',
  'Filtrar': 'Filter',
  'Personal': 'Personal',
  'Global': 'Global',
  'Obligatorio': 'Required',
  'Opcional': 'Optional',
  'obligatorio': 'required',
  'opcional': 'optional',

  // ── Perfil ────────────────────────────────────────────────────────────────
  'Mi perfil': 'My profile',
  'Tema de la plataforma': 'Platform theme',
  'Idioma de la plataforma': 'Platform language',
  'Cuentas IA a las que perteneces': 'AI accounts you belong to',
  'Cambiar foto': 'Change photo',
  'Miembro': 'Member',
  'Sin cuentas asignadas.': 'No accounts assigned.',
  'Ir al panel superadmin': 'Go to superadmin panel',
  'URL de la foto (https://…)': 'Photo URL (https://…)',
  'Actual': 'Default',
  'Claro': 'Light',
  'Oscuro': 'Dark',
  'Gris': 'Gray',

  // ── Inbox ─────────────────────────────────────────────────────────────────
  'Conversaciones': 'Conversations',
  'Conversación': 'Conversation',
  'Sin conversaciones': 'No conversations',
  'Selecciona una conversación': 'Select a conversation',
  'Escribe un mensaje...': 'Type a message...',
  'Escribe un mensaje…': 'Type a message…',
  'Responder': 'Reply',
  'Responder...': 'Reply...',
  'No leídos': 'Unread',
  'Sin leer': 'Unread',
  'Asignadas a mí': 'Assigned to me',
  'Guardar filtro': 'Save filter',
  'Filtros guardados': 'Saved filters',
  'Nombre del filtro': 'Filter name',
  'Asistente': 'Assistant',
  'Asesor': 'Agent',
  'Cliente': 'Customer',
  'En línea': 'Online',
  'Desconectado': 'Offline',
  'Escribiendo…': 'Typing…',

  // ── CRM / Pipeline ────────────────────────────────────────────────────────
  'Dashboard': 'Dashboard',
  'Pipeline': 'Pipeline',
  'Contactos': 'Contacts',
  'Contacto': 'Contact',
  'Tareas': 'Tasks',
  'Tarea': 'Task',
  'Notas': 'Notes',
  'Nota': 'Note',
  'Nuevo contacto': 'New contact',
  'Nueva tarea': 'New task',
  'Teléfono': 'Phone',
  'Correo': 'Email',
  'Empresa': 'Company',
  'Valor': 'Value',
  'Prioridad': 'Priority',
  'Vencimiento': 'Due date',
  'Importar contactos': 'Import contacts',
  'Exportar contactos': 'Export contacts',

  // ── Campañas / Masivos ────────────────────────────────────────────────────
  'Nueva campaña': 'New campaign',
  'Nombre de la campaña': 'Campaign name',
  'Flujo a ejecutar (contiene la plantilla)': 'Flow to run (contains the template)',
  'Programar': 'Schedule',
  'Crear y enviar ya': 'Create and send now',
  'Enviar ya': 'Send now',
  'Audiencia': 'Audience',
  'Borrador': 'Draft',
  'Programada': 'Scheduled',
  'Enviando…': 'Sending…',
  'Enviada': 'Sent',
  'Cancelada': 'Cancelled',
  'Sin campañas todavía.': 'No campaigns yet.',

  // ── Flujos ────────────────────────────────────────────────────────────────
  'Flujo': 'Flow',
  'Nuevo flujo': 'New flow',
  'Editor de flujos': 'Flow editor',
  'Nodos': 'Nodes',
  'Nodo': 'Node',
  'Guardar flujo': 'Save flow',
  'Ejecutar': 'Run',
  'Ejecutar un flujo': 'Run a flow',
  'Prueba': 'Test',
  'Variables': 'Variables',
  'Variable': 'Variable',
  'Herramientas IA': 'AI Tools',
  'Herramienta IA Especial': 'Special AI Tool',
  'Nueva herramienta': 'New tool',
  'Crear herramienta': 'Create tool',
  'Acción al invocar': 'Action when invoked',
  'Solo guardar variables': 'Only save variables',
  'Campos a recolectar': 'Fields to collect',
  'Sin campos definidos': 'No fields defined',
  'Sin asignar a ningún prompt': 'Not assigned to any prompt',

  // ── Config / Canales / Prompts ────────────────────────────────────────────
  'Canales': 'Channels',
  'Prompts': 'Prompts',
  'Prompt': 'Prompt',
  'Prompt activo': 'Active prompt',
  'Miembros': 'Members',
  'Roles': 'Roles',
  'Rol': 'Role',
  'Permisos': 'Permissions',
  'Modelo': 'Model',
  'Modelo base': 'Base model',
  'Mensaje de bienvenida': 'Welcome message',
  'System prompt inicial': 'Initial system prompt',
  'Temperatura': 'Temperature',
  'Conocimiento': 'Knowledge',
  'Base de conocimiento': 'Knowledge base',
  'Respaldo': 'Backup',
  'Copia de seguridad': 'Backup',
  'Conectado': 'Connected',
  'No conectado': 'Not connected',
  'Desconectado': 'Disconnected',

  // ── Soporte (tickets) ─────────────────────────────────────────────────────
  'Tickets de soporte': 'Support tickets',
  'Ticket': 'Ticket',
  'Abierto': 'Open',
  'En progreso': 'In progress',
  'Cerrado': 'Closed',
  'Sin tickets': 'No tickets',
  'Selecciona un ticket': 'Select a ticket',
  'Chats referenciados:': 'Referenced chats:',
  'Responder como Soporte AVI...': 'Reply as AVI Support...',
  'Ticket cerrado': 'Ticket closed',

  // ── API keys / integraciones ──────────────────────────────────────────────
  'API Keys (entrante)': 'API Keys (inbound)',
  'Nueva API key': 'New API key',
  'Nombre descriptivo': 'Descriptive name',
  'Permisos (scopes)': 'Permissions (scopes)',
  'Generar key': 'Generate key',
  'Sin API keys todavía.': 'No API keys yet.',

  // ── Superadmin ────────────────────────────────────────────────────────────
  'Gestión de cuentas': 'Account management',
  'Crear cuenta': 'Create account',
  'Nueva cuenta': 'New account',
  'Agentes IA de': 'AI agents of',
  'Nombre del agente': 'Agent name',
  'Plataforma (default)': 'Platform (default)',
  'Configuración de la plataforma': 'Platform settings',

  // ── Estados / mensajes varios ─────────────────────────────────────────────
  'Sí, eliminar': 'Yes, delete',
  'Sin resultados': 'No results',
  'No hay datos': 'No data',
  'Vacío': 'Empty',
  'Error': 'Error',
  'Éxito': 'Success',
  'Advertencia': 'Warning',
  'Guardado': 'Saved',
  'Guardado ✓': 'Saved ✓',
  'Herramienta creada ✓': 'Tool created ✓',
  'Herramienta actualizada ✓': 'Tool updated ✓',
  'Hoy': 'Today',
  'Ayer': 'Yesterday',
  'Ahora': 'Now',

  // ── Autenticación / acceso ────────────────────────────────────────────────
  'Iniciar sesión': 'Sign in',
  'Cerrar sesión': 'Log out',
  'Correo electrónico': 'Email',
  'Contraseña': 'Password',
  'Recordarme': 'Remember me',
  '¿Olvidaste tu contraseña?': 'Forgot your password?',
  'Crear cuenta': 'Create account',
  'Bienvenido': 'Welcome',
  'Bienvenido de nuevo': 'Welcome back',
  'Registrarse': 'Sign up',
  'Aceptar invitación': 'Accept invitation',

  // ── Configuración / canales ───────────────────────────────────────────────
  'Ajustes': 'Settings',
  'General': 'General',
  'Apariencia': 'Appearance',
  'Notificaciones': 'Notifications',
  'Seguridad': 'Security',
  'Idioma': 'Language',
  'Tema': 'Theme',
  'Zona horaria': 'Time zone',
  'Conectar canal': 'Connect channel',
  'Conectar WhatsApp': 'Connect WhatsApp',
  'Número de teléfono': 'Phone number',
  'Estado del canal': 'Channel status',
  'Webchat': 'Webchat',
  'Código de inserción': 'Embed code',
  'Copiar código': 'Copy code',
  'Clave API': 'API key',
  'Clave de OpenAI': 'OpenAI key',
  'Clave de Anthropic': 'Anthropic key',
  'Clave de DeepSeek': 'DeepSeek key',
  'Guardar configuración': 'Save settings',

  // ── Conocimiento / RAG ────────────────────────────────────────────────────
  'Base de conocimiento': 'Knowledge base',
  'Archivos': 'Files',
  'Archivo': 'File',
  'Subir archivo': 'Upload file',
  'Subir archivos': 'Upload files',
  'Documentos': 'Documents',
  'Activar conocimiento': 'Enable knowledge',
  'Sin archivos todavía': 'No files yet',
  'Procesando…': 'Processing…',
  'Indexado': 'Indexed',
  'Biblioteca de recursos': 'Resource library',
  'Recursos': 'Resources',
  'Recurso': 'Resource',
  'Carpetas': 'Folders',
  'Carpeta': 'Folder',
  'Categorías': 'Categories',
  'Categoría': 'Category',
  'Nueva carpeta': 'New folder',

  // ── Métricas / analítica ──────────────────────────────────────────────────
  'Resumen': 'Summary',
  'Total': 'Total',
  'Mensajes': 'Messages',
  'Mensaje': 'Message',
  'Conversaciones totales': 'Total conversations',
  'Tokens usados': 'Tokens used',
  'Uso de tokens': 'Token usage',
  'Costo': 'Cost',
  'Periodo': 'Period',
  'Esta semana': 'This week',
  'Este mes': 'This month',
  'Últimos 7 días': 'Last 7 days',
  'Últimos 30 días': 'Last 30 days',
  'Sin datos para este periodo': 'No data for this period',
  'Promedio': 'Average',
  'Historial': 'History',
  'Historial de prompts': 'Prompt history',

  // ── Flujos (paleta de nodos) ──────────────────────────────────────────────
  'Mensaje de texto': 'Text message',
  'Botones': 'Buttons',
  'Lista': 'List',
  'Condición': 'Condition',
  'Esperar': 'Wait',
  'Esperar input': 'Wait for input',
  'Asignar conversación': 'Assign conversation',
  'Agente IA': 'AI Agent',
  'Chat IA': 'AI Chat',
  'Clasificador de intención': 'Intent classifier',
  'Extractor de entidades': 'Entity extractor',
  'Sentimiento': 'Sentiment',
  'Resumidor': 'Summarizer',
  'Reescritor': 'Rewriter',
  'Router IA': 'AI Router',
  'HTTP request': 'HTTP request',
  'API personalizada': 'Custom API',
  'CRM (acción)': 'CRM (action)',
  'Guardar en CRM': 'Save to CRM',
  'Enviar plantilla WhatsApp': 'Send WhatsApp template',
  'Disparar': 'Trigger',
  'Inicio': 'Start',
  'Fin': 'End',
  'Arrastra un nodo aquí': 'Drag a node here',
  'Añadir nodo': 'Add node',
  'Duplicar': 'Duplicate',
  'Eliminar nodo': 'Delete node',
  'Marcar como inicio': 'Set as start',

  // ── Mensajes de estado / errores comunes ──────────────────────────────────
  'Algo salió mal': 'Something went wrong',
  'Inténtalo de nuevo': 'Try again',
  'No se pudo guardar': 'Could not save',
  'No se pudo cargar': 'Could not load',
  'Cambios guardados': 'Changes saved',
  'Operación completada': 'Operation completed',
  'Campo requerido': 'Required field',
  'Selecciona una opción': 'Select an option',
  'Selecciona un agente': 'Select an agent',
  '¿Estás seguro?': 'Are you sure?',
  'Esta acción no se puede deshacer': 'This action cannot be undone',
  'No hay nada aquí todavía': 'Nothing here yet',
  'Próximamente': 'Coming soon',
  'Pendiente': 'Pending',
  'Completado': 'Completed',
  'En curso': 'In progress',
  'Fallido': 'Failed',
  'Correcto': 'OK',
  'Conectando...': 'Connecting...',
  'Reintentar': 'Retry',
  'Actualizar': 'Refresh',
  'Volver a la lista': 'Back to list',
  'Sin asignar': 'Unassigned',
  'Asignado a': 'Assigned to',
  'Activa': 'Active',
  'Inactivo': 'Inactive',
  'Suspendida': 'Suspended',
  'Vencida': 'Expired',
  'Activar': 'Enable',
  'Desactivar': 'Disable',

  // ── SuperAdmin: navegación + suscripciones ────────────────────────────────
  'Supervisión': 'Supervision',
  'Supervisión de cuentas': 'Account supervision',
  'Comercial': 'Commercial',
  'Tipos de cuenta': 'Account types',
  'Tipos de Cuenta': 'Account Types',
  'Mensualidades': 'Plans',
  'Demos': 'Demos',
  'Config Demo': 'Demo config',
  'Configuración de Demo': 'Demo configuration',
  'Antifraude Demo': 'Demo anti-fraud',
  'Pricing IA': 'AI Pricing',
  'Tipo de cuenta': 'Account type',
  'Plan mensual': 'Monthly plan',
  'Suscripción': 'Subscription',
  'Estado de la suscripción': 'Subscription status',
  'Consumo': 'Usage',
  'Consumo del plan': 'Plan usage',
  'Conversaciones': 'Conversations',
  'Conversaciones utilizadas': 'Conversations used',
  'Conversaciones restantes': 'Conversations remaining',
  'Conversaciones disponibles': 'Conversations available',
  'Límite mensual de conversaciones': 'Monthly conversation limit',
  'Periodo de gracia': 'Grace period',
  'Periodo de gracia (días)': 'Grace period (days)',
  'Precio mensual (USD)': 'Monthly price (USD)',
  'Nuevo tipo': 'New type',
  'Nuevo tipo de cuenta': 'New account type',
  'Nuevo plan': 'New plan',
  'Es tipo Demo (vigencia limitada y topes de uso)': 'Is a Demo type (limited validity and usage caps)',
  'Vigencia (días)': 'Validity (days)',
  'Máx. conversaciones': 'Max. conversations',
  'Reactivar': 'Reactivate',
  'Suspender': 'Suspend',
  'Reiniciar consumo': 'Reset usage',
  'Día al día': 'Up to date',
  'Al día': 'Up to date',
  'Próximas a vencer': 'Due soon',
  'En período de gracia': 'In grace period',
  'En riesgo de cancelación': 'At cancellation risk',
  'Cercanas al límite': 'Near the limit',
  'Mayor consumo': 'Highest usage',
  'Oportunidades de upgrade': 'Upgrade opportunities',
  'Cuentas totales': 'Total accounts',
  'De pago': 'Paid',
  'Sin asignar': 'Unassigned',
  'Centro de alertas': 'Alert center',
  'Buscar cuenta/correo…': 'Search account/email…',

  // ── Comercial / reportes ──────────────────────────────────────────────────
  'Dashboard comercial': 'Commercial dashboard',
  'Ingresos por plan': 'Revenue by plan',
  'Conversiones Demo→Pago': 'Demo→Paid conversions',
  'Tasa de conversión': 'Conversion rate',
  'Cuentas nuevas del mes': 'New accounts this month',
  'Conversaciones del ciclo': 'Conversations this cycle',
  'Reportes exportables': 'Exportable reports',
  'Consumo mensual': 'Monthly usage',
  'Conversaciones por cuenta': 'Conversations per account',
  'Cuentas suspendidas': 'Suspended accounts',
  'Uso de canales por cuenta': 'Channel usage per account',

  // ── Demo / onboarding ─────────────────────────────────────────────────────
  'Prueba gratis': 'Free trial',
  'Crear mi IA': 'Create my AI',
  'Creando tu IA…': 'Creating your AI…',
  'Probar mi IA': 'Try my AI',
  'Ir al panel de control →': 'Go to dashboard →',
  '¡Tu IA está lista!': 'Your AI is ready!',
  'Tus datos': 'Your details',
  'Tu IA': 'Your AI',
  'Diagnóstico del negocio': 'Business discovery',
  'Plantilla de descubrimiento': 'Discovery template',
  'Descargar plantilla': 'Download template',
  'Nombre de la IA': 'AI name',
  'Industria o sector': 'Industry or sector',
  'Tipo de negocio': 'Business type',
  'Objetivo principal de la IA': 'Main goal of the AI',
  'Nombre completo': 'Full name',
  'Nombre de la empresa': 'Company name',
  'País': 'Country',
  'Ciudad': 'City',
  'Sitio web (opcional)': 'Website (optional)',
  'Ya tengo cuenta': 'I already have an account',
  'Continuar →': 'Continue →',
  '← Atrás': '← Back',
  'Registro temporalmente cerrado': 'Registration temporarily closed',
  'Registro de cuentas Demo': 'Demo account registration',
  'Plantilla de Descubrimiento Empresarial': 'Business Discovery Template',
  'Subir plantilla': 'Upload template',
  'Dashboard de Demos': 'Demos dashboard',
  'Demos creadas': 'Demos created',
  'Convertidas a pago': 'Converted to paid',
  'Próximas a vencer (3d)': 'Due soon (3d)',
  'Industrias más registradas': 'Top industries',
  'Países con más registros': 'Top countries',
  'Más utilizadas': 'Most used',
  'Mayor probabilidad de conversión': 'Highest conversion probability',
  'Convertidas a pago': 'Converted to paid',
  'Próximas a expirar': 'Expiring soon',

  // ── Inbox / chat acciones ─────────────────────────────────────────────────
  'Responder citando este mensaje': 'Reply quoting this message',
  'Asistente IA': 'AI Assistant',
  'Flujo activo': 'Flow running',
  'Sin mensajes todavía': 'No messages yet',
  'Escribe tu mensaje': 'Type your message',
  'Adjuntar': 'Attach',
  'Nota interna': 'Internal note',
  'Asignar a': 'Assign to',
  'Marcar como leído': 'Mark as read',
  'Marcar como no leído': 'Mark as unread',
  'Cliente': 'Customer',
  'Asistente': 'Assistant',
  'Asesor': 'Agent',
  'Equipo': 'Team',

  // ── Config sub-pestañas / agente ──────────────────────────────────────────
  'Disponibilidad': 'Availability',
  'Estado': 'Status',
  'Activo': 'Active',
  'Borrador': 'Draft',
  'Flujo de entrada principal': 'Main entry flow',
  'Flujo de pruebas': 'Test flow',
  'Flujos de entrada': 'Entry flows',
  'Cuenta': 'Account',
  'Información general': 'General information',
  'Creada el': 'Created on',
  'Vence el': 'Expires on',
  'Días para el próximo pago': 'Days until next payment',
  'Renovar suscripción': 'Renew subscription',
  'Cambiar de plan': 'Change plan',
  'Contactar equipo comercial': 'Contact sales team',
}
